main: net.warvale.conquest.ConquestCore
name: ConquestCore
version: 1.1.4
author: Warvale
description: A CTF plugin.
depend: [StaffCore]
softdepend: [iDisguise]
commands:
  gamever:
    description: Test if the core of the plugin is functioning.
  join:
    description: Join the game.
  leave:
    description: Leave the game.
  start:
    description: Automatically start the game.
  kits:
    description: Opens the kit selection menu.
  vote:
    description: Use this to vote for which map is played.
  setstate:
    description: Sets the state of the game.
  setdebug:
    description: sets the debug mode
  setlobby:
    description: sets the lobby spawn
  stopgame:
    description: Stops the game