main: net.warvale.conquest.Conquest
name: Conquest
version: 1.0.0
author: Warvale
description: Warvale's conquest
commands:
    forcestart:
        description: Starts the game without the countdown.
    forceend:
        description: Ends the game right now.
    gamestate:
        description: Display's the current game state. Mainly used for debugging.
    maps:
        description: Display's all maps.